# Generated by Django 4.2.26 on 2025-11-25 14:01

from django.db import migrations, models
import django.db.models.deletion
import trade_api.models.trade
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trading_entity', models.CharField(max_length=300)),
                ('counterparty', models.CharField(max_length=300)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('style', models.CharField(default='forward', max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('underlying', models.JSONField(default=list, validators=[trade_api.models.trade.validate_three_char_list])),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending approval', 'Pending Approval'), ('needs reapproval', 'Needs Reapproval'), ('approved', 'Approved'), ('sent', 'Sent'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(editable=False)),
                ('action', models.CharField(editable=False, max_length=50)),
                ('state_before', models.CharField(choices=[('draft', 'Draft'), ('pending approval', 'Pending Approval'), ('needs reapproval', 'Needs Reapproval'), ('approved', 'Approved'), ('sent', 'Sent'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], editable=False, max_length=50)),
                ('state_after', models.CharField(choices=[('draft', 'Draft'), ('pending approval', 'Pending Approval'), ('needs reapproval', 'Needs Reapproval'), ('approved', 'Approved'), ('sent', 'Sent'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], editable=False, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('diff', models.JSONField(default=dict, editable=False)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='trade_api.trade')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
