# Generated by Django 4.2.26 on 2025-11-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradelog',
            options={},
        ),
    ]
