# Generated by Django 4.2.26 on 2025-11-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_api', '0002_alter_tradelog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='value_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
