# Generated by Django 4.2.26 on 2025-11-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_api', '0003_alter_trade_delivery_date_alter_trade_trade_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='action',
            field=models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('cancel', 'Cancel'), ('update', 'Update'), ('send', 'Send'), ('book', 'Book')], editable=False, max_length=10),
        ),
    ]
