# Generated by Django 4.2.26 on 2025-11-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_api', '0004_alter_tradelog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelog',
            name='state_after',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='state_before',
        ),
        migrations.AddField(
            model_name='tradelog',
            name='new_state',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='previous_state',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='trade',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='trade_api.trade'),
        ),
    ]
